// project5/src/pages/ProfilePage.jsx
import { useState, useEffect } from "react";
import { User, Lock, MapPin, ShoppingBag, Check } from "lucide-react";
import { Link } from "react-router-dom";

export default function Profile() {
    const [form, setForm] = useState({
        firstName: "",
        lastName: "",
        email: "",
        phone: "",
        gender: "",
        dob: "",
        country: "",
        state: "",
        avatar: "",
    });

    useEffect(() => {
        const saved = localStorage.getItem("profile");
        if (saved) {
            setForm(JSON.parse(saved));
        }
    }, []);

    const handleChange = (e) => {
        setForm({ ...form, [e.target.name]: e.target.value });
    };

    const handleUpload = (e) => {
        const file = e.target.files[0];
        if (file) {
            const reader = new FileReader();
            reader.onloadend = () => {
                setForm((prev) => ({ ...prev, avatar: reader.result }));
            };
            reader.readAsDataURL(file);
        }
    };

    const handleSave = () => {
        localStorage.setItem("profile", JSON.stringify(form));
        alert("Profile saved!");
    };

    return (
        <div className="min-h-screen bg-gray-50 p-6">
            <div className="max-w-6xl mx-auto grid grid-cols-12 gap-6">
                <aside className="col-span-3 bg-white rounded-xl shadow p-4 space-y-4">
                    <nav className="text-sm text-gray-500 mb-4">
                        <Link to="/" className="hover:underline text-blue-600">
                            Home 
                        </Link>
                        /
                        <Link
                            to="/profile"
                            className="text-blue-600 hover:underline"
                        >
                            Profile
                        </Link>
                    </nav>
                    <h2 className="font-semibold text-xl mt-3">My Profile</h2>
                    <Link
                        to="/profile"
                        className="flex items-center gap-3 w-full px-4 py-3 hover:bg-gray-100 rounded-lg"
                    >
                        <User size={18} /> User Information
                    </Link>
                    <Link
                        to="/change-password"
                        className="flex items-center gap-3 w-full px-4 py-3 hover:bg-gray-100 rounded-lg"
                    >
                        <Lock size={18} /> Change Password
                    </Link>
                    <Link
                        to="/address-book"
                        className="flex items-center gap-3 w-full px-4 py-3 hover:bg-gray-100 rounded-lg"
                    >
                        <MapPin size={18} /> Address Book
                    </Link>
                    <Link
                        to="/orders"
                        className="flex items-center gap-3 w-full px-4 py-3 hover:bg-gray-100 rounded-lg"
                    >
                        <ShoppingBag size={18} /> My Orders
                    </Link>
                </aside>
                <section className="col-span-9 bg-white rounded-xl shadow p-8">
                    <h2 className="text-xl font-semibold mb-1">
                        User Information
                    </h2>
                    <p className="text-sm mb-6">
                        Your information will be stored here
                    </p>

                    <div className="flex items-center gap-4 mb-8">
                        <div className="w-16 h-16 rounded-full bg-gray-200 flex items-center justify-center overflow-hidden">
                            {form.avatar ? (
                                <img
                                    src={form.avatar}
                                    alt="avatar"
                                    className="w-full h-full object-cover"
                                />
                            ) : (
                                <User size={28} className="text-gray-500" />
                            )}
                        </div>
                        <div>
                            <label className="px-4 py-2 border rounded-lg hover:bg-gray-100 cursor-pointer">
                                Upload photo
                                <input
                                    type="file"
                                    accept="image/*"
                                    onChange={handleUpload}
                                    className="hidden"
                                />
                            </label>
                            <p className="text-sm text-gray-500 mt-3">
                                Supported formats: PNG, JPG. Max size: 5MB
                            </p>
                        </div>
                    </div>

                    <form className="grid grid-cols-2 gap-6">
                        <div>
                            <label className="block text-sm mb-1">
                                First name
                            </label>
                            <input
                                type="text"
                                name="firstName"
                                value={form.firstName}
                                onChange={handleChange}
                                className="w-full border rounded-lg px-3 py-2"
                            />
                        </div>
                        <div>
                            <label className="block text-sm mb-1">
                                Last name
                            </label>
                            <input
                                type="text"
                                name="lastName"
                                value={form.lastName}
                                onChange={handleChange}
                                className="w-full border rounded-lg px-3 py-2"
                            />
                        </div>

                        <div>
                            <label className="block text-sm mb-1">Email</label>
                            <input
                                type="email"
                                name="email"
                                disabled
                                value={form.email}
                                className="w-full border rounded-lg px-3 py-2 bg-gray-100"
                            />
                        </div>
                        <div>
                            <label className="block text-sm mb-1">
                                Phone number
                            </label>
                            <input
                                type="text"
                                name="phone"
                                value={form.phone}
                                onChange={handleChange}
                                className="w-full border rounded-lg px-3 py-2"
                            />
                        </div>

                        <div>
                            <label className="block text-sm mb-1">Gender</label>
                            <select
                                name="gender"
                                value={form.gender}
                                onChange={handleChange}
                                className="w-full border rounded-lg px-3 py-2"
                            >
                                <option>Male</option>
                                <option>Female</option>
                                <option>Other</option>
                            </select>
                        </div>
                        <div>
                            <label className="block text-sm mb-1">
                                Date of birth
                            </label>
                            <input
                                type="date"
                                name="dob"
                                value={form.dob}
                                onChange={handleChange}
                                className="w-full border rounded-lg px-3 py-2"
                            />
                        </div>

                        <div>
                            <label className="block text-sm mb-1">
                                Country
                            </label>
                            <input
                                type="text"
                                name="country"
                                value={form.country}
                                onChange={handleChange}
                                className="w-full border rounded-lg px-3 py-2"
                            />
                        </div>
                        <div>
                            <label className="block text-sm mb-1">State</label>
                            <input
                                type="text"
                                name="state"
                                value={form.state}
                                onChange={handleChange}
                                className="w-full border rounded-lg px-3 py-2"
                            />
                        </div>
                    </form>

                    <div className="mt-8">
                        <button
                            type="button"
                            onClick={handleSave}
                            className="flex items-center gap-2 bg-black text-white px-6 py-3 rounded-lg hover:bg-gray-800"
                        >
                            <Check size={18} /> Save changes
                        </button>
                    </div>
                </section>
            </div>
        </div>
    );
}

// project2/src/pages/ProfilePage.vue
<template>
    <div class="flex justify-center items-center bg-gray-100">
        <!-- Container chứa Sidebar và Form content -->
        <div class="flex w-full max-w-8xl bg-gray-300 py-16 px-20 gap-10">
            <!-- Sidebar Container -->
            <div
                class="w-1/4 bg-white shadow-md rounded-lg p-8 flex flex-col justify-between"
            >
                <div class="flex flex-col items-center">
                    <div
                        class="w-32 h-32 bg-gray-200 rounded-full flex items-center justify-center text-5xl mb-4"
                    >
                        👤
                    </div>
                    <p class="font-bold text-lg">{{ userName }}</p>
                    <!-- Hiển thị tên người dùng -->
                </div>
                <ul class="mt-6 space-y-4 text-lg text-gray-700">
                    <li>
                        <router-link
                            to="/profile"
                            class="font-medium flex items-center gap-2 hover:text-green-500"
                        >
                            📝 Thông tin cá nhân
                        </router-link>
                    </li>
                    <li>
                        <router-link
                            to="/address"
                            class="font-medium flex items-center gap-2 hover:text-green-500"
                        >
                            📍 Cài đặt địa chỉ
                        </router-link>
                    </li>
                    <li>
                        <router-link
                            to="/orders"
                            class="font-medium flex items-center gap-2 hover:text-green-500"
                        >
                            🛒 Quản lý đơn hàng
                        </router-link>
                    </li>
                    <li>
                        <router-link
                            to="/saved-codes"
                            class="font-medium flex items-center gap-2 hover:text-green-500"
                        >
                            🔖 Mã đã lưu
                        </router-link>
                    </li>
                    <li>
                        <router-link
                            to="/signin"
                            class="font-medium flex items-center gap-2 hover:text-red-500"
                        >
                            🚪 Đăng xuất
                        </router-link>
                    </li>
                </ul>
            </div>

            <!-- Form Content Container -->
            <div
                class="w-3/4 mx-auto bg-white p-6 rounded-lg shadow-lg"
            >
                <form class="space-y-6" @submit.prevent="handleSubmit">
                    <div class="grid grid-cols-2 gap-5">
                        <div>
                            <label class="block font-bold mb-4">Họ tên:</label>
                            <input
                                type="text"
                                v-model="form.fullName"
                                placeholder="Nhập họ tên"
                                class="w-full border rounded px-4 py-3"
                            />
                        </div>
                        <div>
                            <label class="block font-bold mb-4"
                                >Giới tính:</label
                            >
                            <select
                                v-model="form.gender"
                                class="w-full border rounded px-4 py-3"
                            >
                                <option value="">Lựa chọn</option>
                                <option value="Nam">Nam</option>
                                <option value="Nữ">Nữ</option>
                                <option value="Khác">Khác</option>
                            </select>
                        </div>
                        <div>
                            <label class="block font-bold mb-4"
                                >Số điện thoại:</label
                            >
                            <input
                                type="text"
                                v-model="form.phone"
                                placeholder="Nhập số điện thoại"
                                class="w-full border rounded px-4 py-3"
                            />
                        </div>
                        <div class="grid grid-cols-3 gap-4">
                            <div>
                                <label class="block font-bold mb-4"
                                    >Ngày sinh:</label
                                >
                                <select
                                    v-model="form.day"
                                    class="w-full border rounded px-4 py-3"
                                >
                                    <option>Ngày</option>
                                    <option v-for="n in 31" :key="n" :value="n">
                                        {{ n }}
                                    </option>
                                </select>
                            </div>
                            <div>
                                <label class="block font-bold mb-4 invisible"
                                    >Tháng</label
                                >
                                <select
                                    v-model="form.month"
                                    class="w-full border rounded px-4 py-3"
                                >
                                    <option>Tháng</option>
                                    <option v-for="n in 12" :key="n" :value="n">
                                        {{ n }}
                                    </option>
                                </select>
                            </div>
                            <div>
                                <label class="block font-bold mb-4 invisible"
                                    >Năm</label
                                >
                                <select
                                    v-model="form.year"
                                    class="w-full border rounded px-4 py-3"
                                >
                                    <option>Năm</option>
                                    <option
                                        v-for="n in 100"
                                        :key="n"
                                        :value="2025 - n"
                                    >
                                        {{ 2025 - n }}
                                    </option>
                                </select>
                            </div>
                        </div>
                        <div class="col-span-2">
                            <label class="block font-bold mb-4">Email:</label>
                            <input
                                type="email"
                                v-model="form.email"
                                placeholder="Nhập email nhận ưu đãi"
                                class="w-full border rounded px-4 py-3"
                            />
                        </div>
                    </div>

                    <div class="flex justify-center">
                        <button
                            type="submit"
                            class="bg-orange-600 text-white font-bold px-6 py-3 rounded hover:bg-orange-700 mt-5"
                        >
                            Lưu thông tin
                        </button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</template>

<script setup>
import { reactive, ref, onMounted } from "vue";

// Khai báo form với reactive
const form = reactive({
    fullName: "",
    gender: "",
    phone: "",
    email: "",
    day: "",
    month: "",
    year: "",
});

const userName = ref("Nguyễn Văn A"); // Tên mặc định

// Hàm được gọi khi component được tạo ra để tải dữ liệu từ localStorage
onMounted(() => {
    const savedUser = localStorage.getItem("user");
    if (savedUser) {
        const savedData = JSON.parse(savedUser);
        form.fullName = savedData.fullName || "";
        form.gender = savedData.gender || "";
        form.phone = savedData.phone || "";
        form.email = savedData.email || "";
        form.day = savedData.day || "";
        form.month = savedData.month || "";
        form.year = savedData.year || "";
        userName.value = form.fullName || "Nguyễn Văn A"; // Cập nhật tên người dùng
    }
});

// Hàm xử lý gửi form
const handleSubmit = () => {
    // Kiểm tra tất cả các trường đã được điền chưa
    if (
        !form.fullName ||
        !form.gender ||
        !form.phone ||
        !form.email ||
        !form.day ||
        !form.month ||
        !form.year
    ) {
        alert("Vui lòng điền đầy đủ thông tin!");
    } else {
        // Lưu thông tin vào localStorage
        localStorage.setItem("user", JSON.stringify(form));

        // Cập nhật tên người dùng
        userName.value = form.fullName;

        // Hiển thị thông báo thành công
        alert("Lưu thông tin thành công!");

        // Reset form sau khi lưu thành công
        resetForm();
    }
};

// Hàm reset form
const resetForm = () => {
    form.fullName = "";
    form.gender = "";
    form.phone = "";
    form.email = "";
    form.day = "";
    form.month = "";
    form.year = "";
};
</script>

<style scoped>
/* Optional: Custom styles if needed */
</style>
