// project5/src/pages/SigninPage.jsx
import { useState, useContext } from "react";
import { useNavigate } from "react-router-dom";
import { AuthContext } from "../context/AuthContext";

export default function SigninPage() {
    const navigate = useNavigate();
    const [email, setEmail] = useState("");
    const [password, setPassword] = useState("");
    const { login } = useContext(AuthContext);

    const handleLogin = () => {
        const storedUser = JSON.parse(localStorage.getItem("users"));
        if (!storedUser) {
            alert("No user found. Please sign up first!");
            return;
        }

        if (storedUser.email === email && storedUser.password === password) {
              login(storedUser); // 👉
            alert("Login successful ✅");
            navigate("/");
        } else {
            alert("Invalid email or password ❌");
        }
    };

    return (
        <div className="bg-[url('/images/assets/homebanner.svg')] bg-cover bg-center bg-no-repeat  flex items-center justify-center md:justify-end md:pr-85 ">
            <div className="bg-white text-black rounded-xl p-6 sm:p-8 w-[90%] sm:w-[400px] flex flex-col gap-3 items-center mt-20 md:mt-30 mb-20">
                <h2 className="text-center mb-2 text-xl font-semibold">
                    Login
                </h2>

                {/* Email */}
                <div className="flex flex-col mb-4">
                    <label className="text-[13px] mb-1 font-bold">Email</label>
                    <input
                        type="email"
                        placeholder="Enter your email"
                        value={email}
                        onChange={(e) => setEmail(e.target.value)}
                        className="w-[290px] h-12 px-4 border border-gray-300 rounded-lg text-sm"
                    />
                </div>

                {/* Password */}
                <div className="flex flex-col mb-4">
                    <label className="text-[13px] mb-1 font-bold">
                        Password
                    </label>
                    <div className="relative">
                        <input
                            type="password"
                            placeholder="Enter your password"
                            value={password}
                            onChange={(e) => setPassword(e.target.value)}
                            className="w-[290px] h-12 px-4 pr-10 border border-gray-300 rounded-lg text-sm"
                        />
                        <button
                            type="button"
                            className="absolute right-4 top-1/2 -translate-y-1/2"
                        >
                            👁
                        </button>
                    </div>
                </div>

                {/* Remember me */}
                <div className="flex items-center gap-2 cursor-pointer w-[290px]">
                    <input
                        type="checkbox"
                        id="remember"
                        className="cursor-pointer"
                    />
                    <label
                        htmlFor="remember"
                        className="cursor-pointer text-sm"
                    >
                        Keep me logged in
                    </label>
                </div>

                {/* Login button */}
                <button
                    onClick={handleLogin}
                    className="w-[290px] h-[50px] border border-gray-300 rounded-lg text-sm font-semibold cursor-pointer bg-black hover:bg-blue-500 text-white"
                >
                    Login now
                </button>

                {/* Forgot password */}
                <a href="#" className="flex justify-center text-sm">
                    Forgot your password?
                </a>

                {/* OR */}
                <p className="flex justify-center items-center text-base font-medium text-center w-full">
                    <span className="flex-1 border-b border-gray-300 mr-2"></span>
                    or login with
                    <span className="flex-1 border-b border-gray-300 ml-2"></span>
                </p>

                {/* Social login */}
                <div className="flex justify-center gap-2 w-[290px]">
                    <button className="w-[65px] h-[30px] flex justify-center items-center border cursor-pointer rounded">
                        <img
                            src="/images/assets/fake.svg"
                            alt="facebook"
                            className="w-4 "
                        />
                    </button>
                    <button className="w-[65px] h-[30px] flex justify-center items-center border cursor-pointer rounded">
                        <img
                            src="/images/assets/btnapple.svg"
                            alt="apple"
                            className="w-4"
                        />
                    </button>
                    <button className="w-[65px] h-[30px] flex justify-center items-center cursor-pointer border rounded">
                        <img
                            src="/images/assets/simple-icons_x.svg"
                            alt="twitter"
                            className="w-4"
                        />
                    </button>
                    <button className="w-[65px] h-[30px] flex justify-center items-center cursor-pointer border rounded">
                        <img
                            src="/images/assets/gg.svg"
                            alt="google"
                            className="w-4"
                        />
                    </button>
                </div>

                {/* Signup */}
                <p className="flex justify-center text-sm">
                    You don't have an account?
                </p>
                <button
                    onClick={() => navigate("/email")}
                    className="w-[290px] h-[50px] border border-gray-300 rounded-lg text-sm font-medium cursor-pointer"
                >
                    Create new account
                </button>
            </div>
        </div>
    );
}

// project2/src/pages/SigninPage.vue
<template>
    <div class="flex justify-center items-center min-h-screen bg-gray-100">
        <form
            @submit.prevent="handleSubmit"
            class="bg-white px-10 py-8 rounded shadow-lg w-full max-w-md"
        >
            <div class="flex gap-1 items-center mb-6">
                <p class="font-semibold cursor-pointer" @click="goToHome">
                    Trang Chủ /
                </p>
                <p class="font-semibold cursor-pointer" @click="goToSignup">
                    Đăng Ký
                </p>
            </div>
            <h2 class="text-3xl font-bold mb-6 text-center">Đăng Nhập</h2>

            <div class="mb-6">
                <label class="block text-xl font-semibold mb-2"
                    >Tài khoản</label
                >
                <input
                    v-model="formData.username"
                    type="text"
                    placeholder="Nhập tài khoản"
                    required
                    class="w-full px-4 py-2 border rounded"
                />
            </div>

            <div class="mb-6 relative">
                <label class="block text-xl font-semibold mb-2">Mật khẩu</label>
                <input
                    v-model="formData.password"
                    :type="showPassword ? 'text' : 'password'"
                    placeholder="Nhập mật khẩu"
                    required
                    class="w-full px-4 py-2 border rounded pr-10"
                />
                <span
                    class="absolute top-3/4 right-3 transform -translate-y-1/2 cursor-pointer"
                    @click="togglePasswordVisibility"
                >
                    {{ showPassword ? "🙈" : "👁️" }}
                </span>
            </div>

            <div v-if="error" class="mb-4 text-red-500 text-sm">
                {{ error }}
            </div>

            <button
                type="submit"
                class="w-full bg-orange-600 hover:bg-orange-700 text-white text-lg font-bold py-3 rounded"
            >
                Đăng Nhập
            </button>
        </form>
    </div>
</template>

<script setup>
import { ref } from "vue";
import { useRouter } from "vue-router";
import { useAuthStore } from "../store/authStore";

function goToSignup() {
    router.push("/signup");
}

function goToHome() {
    router.push("/");
}

const router = useRouter();
const auth = useAuthStore();
const formData = ref({ username: "", password: "" });
const error = ref("");
const showPassword = ref(false);

const togglePasswordVisibility = () => {
    showPassword.value = !showPassword.value;
};

const generateToken = () => {
    return btoa(`${formData.value.username}-${Date.now()}-${Math.random()}`);
};

const handleSubmit = () => {
    error.value = "";
    const users = JSON.parse(localStorage.getItem("users") || "[]");
    const found = users.find(
        (u) =>
            u.username === formData.value.username &&
            u.password === formData.value.password
    );

    if (!found) {
        error.value = "Sai tài khoản hoặc mật khẩu";
        return;
    }

    const token = generateToken(); 

    auth.login(token, { username: found.username });
    router.push("/");
};
</script>
