// project3/src/layout/MainLayout.vue
<template>
    <section>
        <Header />
        <main>
            <router-view />
        </main>
        <Footer />
    </section>
</template>

<script>
import Footer from "../components/Footer.vue";
import Header from "../components/Header.vue";
export default {
    name: "MainLayout",
    components: {
        Header,
        Footer,
    },
};
</script>

<style scoped></style>

// project5/src/layouts/MainLayout.jsx
import React from "react";
import Header from "../components/Header";
import { Outlet } from "react-router-dom";
import Footer from "../components/Footer";
function MainLayout() {
    return (
        <div className="min-h-screen flex flex-col">
            <Header />
            <main className="flex-grow">
                <Outlet />
            </main>
            <Footer />
        </div>
    );
}

export default MainLayout;
